version: 2

project_name: streamlink

env:
  - STREAMLINK_VERSION={{ .Env.STREAMLINK_VERSION }}


builds: 
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

dockers_v2:
  - images:
      - "insanity54/streamlink"
      - "ghcr.io/insanity54/streamlink"
    tags:
      - "{{ .Env.STREAMLINK_VERSION }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "streamlink"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Env.STREAMLINK_VERSION}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
