name: Docker Build and Push

on:
  schedule:
    # Runs every 3 days at midnight
    - cron: '0 0 */3 * *'
  push:
    tags:
      - v*

jobs:
  build:
    name: Release Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: stable
      CGO_ENABLED: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Streamlink version from Alpine
        id: get_version
        run: |
          alpine_image="alpine:edge"
          streamlink_version=$(docker run --rm "${alpine_image}" /bin/sh -c "apk update && apk add --no-cache jq && apk info streamlink --format json | jq -r '.[0].version'")
          if [[ -z "$streamlink_version" ]]; then
            echo "Error: Unable to fetch Streamlink version from Alpine"
            exit 1
          fi
          echo "Latest Streamlink version from Alpine is: $streamlink_version"
          echo "STREAMLINK_VERSION=$STREAMLINK_VERSION" >> $GITHUB_ENV

      - name: dockerhub-login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ghcr-login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: insanity54
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # - name: Build Docker Image
      #   run: docker build . -t insanity54/streamlink:${{ env.streamlink_version }}

      # - name: Push Docker Image
      #   run: docker push insanity54/streamlink:${{ env.streamlink_version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "2.14.3"
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          STREAMLINK_VERSION: ${{ env.STREAMLINK_VERSION }}